import type {
  AIInsight,
  ActivityEvent,
  ClaimAttentionItem,
  DashboardMetric,
  OperationalAlert,
  UpcomingRenewal,
  WorkQueueItem,
} from "./types";

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();
const daysFromNow = (d: number) =>
  new Date(now + d * 86_400_000).toISOString();

export const mockMetrics: DashboardMetric[] = [
  {
    id: "open-claims",
    label: "Open claims",
    value: 248,
    trend: 4.2,
    status: "info",
    hint: "32 opened this week",
    iconKey: "claims",
  },
  {
    id: "needs-review",
    label: "Claims needing review",
    value: 41,
    trend: 12,
    status: "warning",
    hint: "12 over 48 hours",
    iconKey: "review",
  },
  {
    id: "expiring",
    label: "Policies expiring (30d)",
    value: 67,
    trend: -3,
    status: "warning",
    hint: "7 high-risk renewals",
    iconKey: "expiring",
  },
  {
    id: "indexing",
    label: "Documents pending indexing",
    value: 19,
    trend: -22,
    status: "info",
    hint: "Avg processing 3m 12s",
    iconKey: "indexing",
  },
  {
    id: "overdue",
    label: "Tasks overdue",
    value: 14,
    trend: 8,
    status: "danger",
    hint: "Across 6 agents",
    iconKey: "overdue",
  },
  {
    id: "ai-questions",
    label: "AI questions today",
    value: 312,
    trend: 18,
    status: "success",
    hint: "94% answered with citations",
    iconKey: "ai",
  },
];

export const mockAlerts: OperationalAlert[] = [
  {
    id: "a1",
    type: "SLA breach",
    priority: "critical",
    message: "12 claims waiting over 48 hours",
    detail: "Auto and Home claims pending initial adjuster review.",
    actionLabel: "Review queue",
  },
  {
    id: "a2",
    type: "Fraud review",
    priority: "critical",
    message: "2 urgent fraud-review flags",
    detail: "AI risk score above 0.85 on commercial auto claims.",
    actionLabel: "Open cases",
  },
  {
    id: "a3",
    type: "Policy gap",
    priority: "high",
    message: "4 policies missing endorsements",
    detail: "Endorsements required before renewal next week.",
    actionLabel: "View policies",
  },
  {
    id: "a4",
    type: "Renewals",
    priority: "high",
    message: "7 renewals expiring this week",
    detail: "Estimated $1.2M in annual premium at risk.",
    actionLabel: "Open renewals",
  },
  {
    id: "a5",
    type: "Document",
    priority: "medium",
    message: "3 uploads failed indexing",
    detail: "OCR confidence below threshold — manual review needed.",
    actionLabel: "Review uploads",
  },
];

export const mockQueue: WorkQueueItem[] = [
  {
    id: "q1",
    title: "Flood damage estimate review",
    reference: "CLM-20458",
    customer: "Reyes Logistics",
    priority: "urgent",
    dueDate: daysFromNow(0.4),
    assignedTo: "Maria Chen",
    category: "claim",
  },
  {
    id: "q2",
    title: "Missing proof-of-loss documents",
    reference: "POL-88291",
    customer: "Adelaide Park",
    priority: "high",
    dueDate: daysFromNow(1),
    assignedTo: "James Okafor",
    category: "document",
  },
  {
    id: "q3",
    title: "Escalated injury claim — legal review",
    reference: "CLM-20312",
    customer: "Northbridge Co.",
    priority: "urgent",
    dueDate: daysFromNow(0.2),
    assignedTo: "Priya Natarajan",
    category: "escalation",
  },
  {
    id: "q4",
    title: "Renewal approval pending",
    reference: "POL-77123",
    customer: "Hartwell Family",
    priority: "high",
    dueDate: daysFromNow(2),
    assignedTo: "Daniel Brooks",
    category: "approval",
  },
  {
    id: "q5",
    title: "Adjuster reassignment — workload",
    reference: "CLM-20501",
    customer: "Skyline Manufacturing",
    priority: "medium",
    dueDate: daysFromNow(3),
    assignedTo: "Unassigned",
    category: "claim",
  },
  {
    id: "q6",
    title: "Inspection report missing",
    reference: "CLM-20489",
    customer: "Coastal Marine LLC",
    priority: "high",
    dueDate: daysFromNow(1.2),
    assignedTo: "Maria Chen",
    category: "document",
  },
];

export const mockActivity: ActivityEvent[] = [
  {
    id: "e1",
    type: "claim_escalated",
    timestamp: minutesAgo(8),
    actor: "Priya Natarajan",
    description: "Escalated to legal review",
    target: "CLM-20312",
  },
  {
    id: "e2",
    type: "document_uploaded",
    timestamp: minutesAgo(22),
    actor: "Adelaide Park",
    description: "Uploaded proof-of-loss documents",
    target: "POL-88291",
  },
  {
    id: "e3",
    type: "ai_question",
    timestamp: minutesAgo(35),
    actor: "Daniel Brooks",
    description: "Asked about flood exclusion clauses",
  },
  {
    id: "e4",
    type: "claim_created",
    timestamp: minutesAgo(58),
    actor: "Reyes Logistics",
    description: "New auto claim filed",
    target: "CLM-20503",
  },
  {
    id: "e5",
    type: "policy_updated",
    timestamp: minutesAgo(95),
    actor: "James Okafor",
    description: "Updated coverage limits",
    target: "POL-77123",
  },
  {
    id: "e6",
    type: "note_added",
    timestamp: minutesAgo(140),
    actor: "Maria Chen",
    description: "Added internal note on inspection delay",
    target: "CLM-20489",
  },
  {
    id: "e7",
    type: "renewal_sent",
    timestamp: minutesAgo(220),
    actor: "System",
    description: "Renewal notice sent to 12 customers",
  },
];

export const mockInsights: AIInsight[] = [
  {
    id: "i1",
    category: "trend",
    title: "Flood claims rising",
    message: "Flood-related claims increased 18% this week, concentrated in the Gulf region.",
    confidence: 92,
    source: "Claims data · last 14 days",
  },
  {
    id: "i2",
    category: "risk",
    title: "Underinsured commercial policies",
    message: "3 commercial policies appear underinsured based on updated property valuations.",
    confidence: 78,
    source: "Policy + market data",
  },
  {
    id: "i3",
    category: "anomaly",
    title: "Document upload failures",
    message: "High document upload failure rate detected on mobile — 14% vs baseline 3%.",
    confidence: 84,
    source: "Document ingestion logs",
  },
  {
    id: "i4",
    category: "opportunity",
    title: "Cross-sell candidates",
    message: "26 home policyholders match auto cross-sell profile with high conversion likelihood.",
    confidence: 71,
    source: "Customer segmentation",
  },
];

export const mockRenewals: UpcomingRenewal[] = [
  {
    id: "r1",
    customer: "Hartwell Family",
    policyType: "Home",
    policyNumber: "POL-77123",
    renewalDate: daysFromNow(3),
    coverageAmount: 485_000,
    risk: "high",
  },
  {
    id: "r2",
    customer: "Northbridge Co.",
    policyType: "Commercial Auto",
    policyNumber: "POL-88001",
    renewalDate: daysFromNow(5),
    coverageAmount: 1_200_000,
    risk: "medium",
  },
  {
    id: "r3",
    customer: "Adelaide Park",
    policyType: "Auto",
    policyNumber: "POL-88291",
    renewalDate: daysFromNow(7),
    coverageAmount: 65_000,
    risk: "low",
  },
  {
    id: "r4",
    customer: "Coastal Marine LLC",
    policyType: "Marine",
    policyNumber: "POL-90112",
    renewalDate: daysFromNow(9),
    coverageAmount: 3_400_000,
    risk: "high",
  },
  {
    id: "r5",
    customer: "Skyline Manufacturing",
    policyType: "Property",
    policyNumber: "POL-91002",
    renewalDate: daysFromNow(12),
    coverageAmount: 5_800_000,
    risk: "medium",
  },
];

export const mockClaimsAttention: ClaimAttentionItem[] = [
  {
    id: "c1",
    reference: "CLM-20312",
    customer: "Northbridge Co.",
    type: "Bodily Injury",
    amount: 240_000,
    reason: "escalated",
    ageDays: 6,
    assignedTo: "Priya Natarajan",
  },
  {
    id: "c2",
    reference: "CLM-20458",
    customer: "Reyes Logistics",
    type: "Flood",
    amount: 92_500,
    reason: "stalled",
    ageDays: 9,
    assignedTo: "Maria Chen",
  },
  {
    id: "c3",
    reference: "CLM-20489",
    customer: "Coastal Marine LLC",
    type: "Marine",
    amount: 415_000,
    reason: "missing_docs",
    ageDays: 4,
    assignedTo: "Maria Chen",
  },
  {
    id: "c4",
    reference: "CLM-20501",
    customer: "Skyline Manufacturing",
    type: "Property",
    amount: 880_000,
    reason: "high_value",
    ageDays: 2,
    assignedTo: "Unassigned",
  },
];
