import type { Task, AutomationSuggestion, WorkflowEvent } from "./types";

const now = Date.now();
const daysFromNow = (d: number) => new Date(now + d * 86400000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3600000).toISOString();

const AGENTS = [
  "Maya Patel",
  "Jordan Reyes",
  "Sam Chen",
  "Priya Nair",
  "Wes Holloway",
  "Lena Müller",
];

export const MOCK_TASKS: Task[] = [
  {
    id: "T-1042",
    title: "Review water damage claim documentation",
    description:
      "Review submitted photos, repair estimates, and adjuster notes for the Hartman water damage claim. Confirm coverage applies before approving payout.",
    priority: "urgent",
    status: "in_progress",
    dueDate: daysAgo(1),
    createdAt: daysAgo(4),
    updatedAt: hoursAgo(3),
    assignedTo: "Maya Patel",
    relatedCustomer: { id: "C-201", name: "Eleanor Hartman" },
    relatedClaim: { id: "CL-8821", reference: "CL-8821" },
    workflowStage: "review",
    workflowType: "claim_review",
    checklist: [
      { id: "ch1", label: "Verify policy coverage", done: true },
      { id: "ch2", label: "Match repair estimates to scope", done: true },
      { id: "ch3", label: "Confirm adjuster assessment", done: false },
      { id: "ch4", label: "Approve or escalate payout", done: false },
    ],
    attachments: [
      { id: "a1", name: "estimate-roof.pdf", sizeKb: 482 },
      { id: "a2", name: "photos-damage.zip", sizeKb: 3104 },
    ],
    notes: [
      {
        id: "n1",
        author: "Jordan Reyes",
        message: "Adjuster report attached. Recommends partial approval pending receipts.",
        timestamp: hoursAgo(20),
      },
    ],
    timeline: [],
  },
  {
    id: "T-1043",
    title: "Collect missing endorsement for auto policy renewal",
    description:
      "Customer's auto policy is missing the rideshare endorsement required for renewal. Request signed form and update file.",
    priority: "high",
    status: "waiting_customer",
    dueDate: daysFromNow(2),
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(6),
    assignedTo: "Jordan Reyes",
    relatedCustomer: { id: "C-118", name: "Marcus Lin" },
    relatedPolicy: { id: "P-4421", number: "AUTO-4421" },
    workflowStage: "pending_docs",
    workflowType: "policy_renewal",
    checklist: [
      { id: "ch1", label: "Send endorsement form", done: true },
      { id: "ch2", label: "Receive signed copy", done: false },
      { id: "ch3", label: "Attach to policy file", done: false },
    ],
    attachments: [{ id: "a1", name: "rideshare-endorsement.pdf", sizeKb: 121 }],
    notes: [],
    timeline: [],
  },
  {
    id: "T-1044",
    title: "Underwriting review — commercial property quote",
    description:
      "New commercial property quote for Briar & Co. requires underwriting sign-off before binding coverage.",
    priority: "high",
    status: "open",
    dueDate: daysFromNow(1),
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(2),
    assignedTo: "Sam Chen",
    relatedCustomer: { id: "C-902", name: "Briar & Co." },
    relatedPolicy: { id: "P-9931", number: "COM-9931" },
    workflowStage: "review",
    workflowType: "underwriting",
    checklist: [
      { id: "ch1", label: "Loss-run review", done: false },
      { id: "ch2", label: "Property inspection report", done: false },
      { id: "ch3", label: "Confirm coverage limits", done: false },
    ],
    attachments: [],
    notes: [],
    timeline: [],
  },
  {
    id: "T-1045",
    title: "Customer callback — coverage gap inquiry",
    description: "Return call to customer regarding their question about umbrella coverage limits.",
    priority: "medium",
    status: "open",
    dueDate: daysFromNow(0),
    createdAt: daysAgo(0),
    updatedAt: hoursAgo(1),
    assignedTo: "Priya Nair",
    relatedCustomer: { id: "C-455", name: "Dana Whitfield" },
    workflowStage: "intake",
    workflowType: "customer_followup",
    checklist: [
      { id: "ch1", label: "Review account history", done: false },
      { id: "ch2", label: "Call customer", done: false },
      { id: "ch3", label: "Log outcome", done: false },
    ],
    attachments: [],
    notes: [],
    timeline: [],
  },
  {
    id: "T-1046",
    title: "Final approval — auto collision claim",
    description: "Claim has cleared review. Final approval needed before payout is issued.",
    priority: "high",
    status: "in_progress",
    dueDate: daysFromNow(1),
    createdAt: daysAgo(6),
    updatedAt: hoursAgo(8),
    assignedTo: "Wes Holloway",
    relatedCustomer: { id: "C-330", name: "Olivia Romero" },
    relatedClaim: { id: "CL-8790", reference: "CL-8790" },
    workflowStage: "approval",
    workflowType: "claim_review",
    checklist: [
      { id: "ch1", label: "Confirm settlement amount", done: true },
      { id: "ch2", label: "Manager sign-off", done: false },
    ],
    attachments: [{ id: "a1", name: "settlement-letter.pdf", sizeKb: 210 }],
    notes: [],
    timeline: [],
  },
  {
    id: "T-1047",
    title: "Compliance audit — Q3 producer licensing",
    description: "Verify all licensed producers have up-to-date CE credits filed for Q3.",
    priority: "low",
    status: "open",
    dueDate: daysFromNow(9),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    assignedTo: "Lena Müller",
    relatedCustomer: { id: "C-INT", name: "Internal Compliance" },
    workflowStage: "intake",
    workflowType: "compliance",
    checklist: [],
    attachments: [],
    notes: [],
    timeline: [],
  },
  {
    id: "T-1048",
    title: "Renewal reminder — homeowners policy",
    description: "Send 30-day renewal reminder for the Patel household homeowners policy.",
    priority: "medium",
    status: "completed",
    dueDate: daysAgo(2),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
    assignedTo: "Maya Patel",
    relatedCustomer: { id: "C-771", name: "Ravi & Anita Patel" },
    relatedPolicy: { id: "P-2210", number: "HOME-2210" },
    workflowStage: "completed",
    workflowType: "policy_renewal",
    checklist: [
      { id: "ch1", label: "Send reminder email", done: true },
      { id: "ch2", label: "Log activity", done: true },
    ],
    attachments: [],
    notes: [],
    timeline: [],
  },
  {
    id: "T-1049",
    title: "Escalation — disputed liability claim",
    description: "Customer disputes liability assessment. Escalate to senior adjuster for re-review.",
    priority: "urgent",
    status: "blocked",
    dueDate: daysFromNow(3),
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(12),
    assignedTo: "Sam Chen",
    relatedCustomer: { id: "C-612", name: "Theodore Banks" },
    relatedClaim: { id: "CL-8755", reference: "CL-8755" },
    workflowStage: "review",
    workflowType: "claim_review",
    checklist: [
      { id: "ch1", label: "Gather dispute documentation", done: true },
      { id: "ch2", label: "Assign senior adjuster", done: false },
    ],
    attachments: [],
    notes: [
      {
        id: "n1",
        author: "Sam Chen",
        message: "Waiting on senior adjuster availability — blocked until Monday.",
        timestamp: hoursAgo(14),
      },
    ],
    timeline: [],
  },
  {
    id: "T-1050",
    title: "Verify proof of prior insurance",
    description: "New auto policy applicant — verify continuous coverage from previous carrier.",
    priority: "medium",
    status: "waiting_customer",
    dueDate: daysFromNow(4),
    createdAt: daysAgo(1),
    updatedAt: hoursAgo(5),
    assignedTo: "Jordan Reyes",
    relatedCustomer: { id: "C-988", name: "Hannah Brooks" },
    workflowStage: "pending_docs",
    workflowType: "document_request",
    checklist: [{ id: "ch1", label: "Request POI letter", done: true }],
    attachments: [],
    notes: [],
    timeline: [],
  },
  {
    id: "T-1051",
    title: "Onboard new commercial account",
    description: "Set up workspace, assign agent, and schedule kickoff call for new commercial client.",
    priority: "medium",
    status: "in_progress",
    dueDate: daysFromNow(5),
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(4),
    assignedTo: "Priya Nair",
    relatedCustomer: { id: "C-1004", name: "Northwind Logistics" },
    workflowStage: "intake",
    workflowType: "customer_followup",
    checklist: [
      { id: "ch1", label: "Create account record", done: true },
      { id: "ch2", label: "Assign account manager", done: true },
      { id: "ch3", label: "Schedule kickoff call", done: false },
    ],
    attachments: [],
    notes: [],
    timeline: [],
  },
  {
    id: "T-1052",
    title: "Document request — medical records",
    description: "Request itemized medical records for active health claim review.",
    priority: "high",
    status: "waiting_customer",
    dueDate: daysAgo(0),
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(7),
    assignedTo: "Wes Holloway",
    relatedCustomer: { id: "C-540", name: "Imani Clarke" },
    relatedClaim: { id: "CL-8801", reference: "CL-8801" },
    workflowStage: "pending_docs",
    workflowType: "document_request",
    checklist: [{ id: "ch1", label: "Send HIPAA authorization", done: true }],
    attachments: [],
    notes: [],
    timeline: [],
  },
  {
    id: "T-1053",
    title: "Approve endorsement — added driver",
    description: "Review and approve added-driver endorsement on auto policy AUTO-3310.",
    priority: "low",
    status: "open",
    dueDate: daysFromNow(6),
    createdAt: daysAgo(0),
    updatedAt: hoursAgo(2),
    assignedTo: "Lena Müller",
    relatedCustomer: { id: "C-220", name: "Felix Tanaka" },
    relatedPolicy: { id: "P-3310", number: "AUTO-3310" },
    workflowStage: "approval",
    workflowType: "underwriting",
    checklist: [],
    attachments: [],
    notes: [],
    timeline: [],
  },
];

export const MOCK_ACTIVITY: WorkflowEvent[] = [
  {
    id: "e1",
    type: "claim_escalated",
    timestamp: hoursAgo(2),
    actor: "Sam Chen",
    description: "Escalated claim CL-8755 to senior adjuster",
    taskId: "T-1049",
  },
  {
    id: "e2",
    type: "customer_responded",
    timestamp: hoursAgo(4),
    actor: "Hannah Brooks",
    description: "Replied to document request",
    taskId: "T-1050",
  },
  {
    id: "e3",
    type: "status_changed",
    timestamp: hoursAgo(6),
    actor: "Jordan Reyes",
    description: "Moved T-1043 to Waiting on Customer",
    taskId: "T-1043",
  },
  {
    id: "e4",
    type: "document_requested",
    timestamp: hoursAgo(8),
    actor: "Wes Holloway",
    description: "Requested medical records from Imani Clarke",
    taskId: "T-1052",
  },
  {
    id: "e5",
    type: "assigned",
    timestamp: hoursAgo(10),
    actor: "Maya Patel",
    description: "Assigned T-1044 to Sam Chen",
    taskId: "T-1044",
  },
  {
    id: "e6",
    type: "created",
    timestamp: hoursAgo(22),
    actor: "Priya Nair",
    description: "Created task T-1045 — callback for Dana Whitfield",
    taskId: "T-1045",
  },
  {
    id: "e7",
    type: "comment_added",
    timestamp: daysAgo(1),
    actor: "Jordan Reyes",
    description: "Commented on T-1042 — review notes added",
    taskId: "T-1042",
  },
  {
    id: "e8",
    type: "status_changed",
    timestamp: daysAgo(2),
    actor: "Maya Patel",
    description: "Completed T-1048 — renewal reminder sent",
    taskId: "T-1048",
  },
];

export const MOCK_AUTOMATIONS: AutomationSuggestion[] = [
  {
    id: "auto1",
    title: "Auto-create senior review task for high-value claims",
    trigger: "When a claim is filed for more than $25,000",
    action: "Create a review task and assign to the on-call senior adjuster",
    category: "claims",
  },
  {
    id: "auto2",
    title: "Flag policies missing required endorsements",
    trigger: "Nightly scan of active auto and commercial policies",
    action: "Open a document-request task for the assigned agent",
    category: "policies",
  },
  {
    id: "auto3",
    title: "Create renewal reminder 30 days before expiration",
    trigger: "30 days before any policy's expiration date",
    action: "Add a renewal task to the policyholder's assigned agent",
    category: "renewals",
  },
  {
    id: "auto4",
    title: "Reopen task if customer does not respond in 5 days",
    trigger: "Task is in Waiting on Customer for 5+ days",
    action: "Send reminder email and re-flag task as overdue",
    category: "documents",
  },
];

export const AGENT_LIST = AGENTS;
