import type { Customer } from "./types";

export const MOCK_AGENTS = [
  "Avery Chen",
  "Marcus Reid",
  "Priya Shah",
  "Jordan Blake",
  "Sofia Martinez",
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "CUS-1042",
    fullName: "Eleanor Whitfield",
    email: "eleanor.whitfield@northbay.com",
    phone: "+1 (415) 555-0182",
    address: "284 Marina Blvd, San Francisco, CA 94123",
    assignedAgent: "Avery Chen",
    status: "high_value",
    tags: ["VIP", "Multi-policy", "Auto-pay"],
    customerSince: "2017-03-12",
    lifetimeValue: 184320,
    lastInteractionAt: "2026-05-12T15:22:00Z",
    policies: [
      {
        id: "POL-AUT-9921",
        type: "auto",
        provider: "Northstar Mutual",
        policyNumber: "NSA-9921-EW",
        premium: 1840,
        coverageLimit: 300000,
        renewalDate: "2026-08-04",
        status: "active",
        coverageSummary: "Full coverage, comprehensive + collision, $500 deductible",
      },
      {
        id: "POL-HOM-4410",
        type: "home",
        provider: "Northstar Mutual",
        policyNumber: "NSH-4410-EW",
        premium: 3240,
        coverageLimit: 1250000,
        renewalDate: "2026-05-30",
        status: "pending_renewal",
        coverageSummary: "Dwelling + personal property, no flood endorsement",
      },
      {
        id: "POL-UMB-2210",
        type: "umbrella",
        provider: "Northstar Mutual",
        policyNumber: "NSU-2210-EW",
        premium: 920,
        coverageLimit: 2000000,
        renewalDate: "2027-01-14",
        status: "active",
        coverageSummary: "Umbrella liability across auto + home",
      },
    ],
    claims: [
      {
        id: "CLM-4421",
        type: "Collision",
        status: "under_review",
        amount: 8420,
        filedAt: "2026-04-22",
        description: "Rear-end collision on US-101, low-speed impact.",
      },
      {
        id: "CLM-4188",
        type: "Property Damage",
        status: "approved",
        amount: 14200,
        filedAt: "2025-11-08",
        description: "Storm damage to roof shingles and gutters.",
      },
    ],
    documents: [
      { id: "D-1", name: "Home_Policy_2026.pdf", category: "policy", sizeKb: 842, uploadedAt: "2026-04-01", status: "indexed" },
      { id: "D-2", name: "Auto_Endorsement_Q1.pdf", category: "endorsement", sizeKb: 312, uploadedAt: "2026-02-14", status: "indexed" },
      { id: "D-3", name: "Roof_Damage_Photos.zip", category: "claim", sizeKb: 5240, uploadedAt: "2025-11-10", status: "indexed" },
      { id: "D-4", name: "Drivers_License.jpg", category: "id", sizeKb: 184, uploadedAt: "2024-08-12", status: "indexed" },
    ],
    notes: [
      { id: "N-1", author: "Avery Chen", message: "Confirmed updated mailing address. Renewal docs sent.", timestamp: "2026-05-12T15:22:00Z", pinned: true },
      { id: "N-2", author: "Marcus Reid", message: "Customer interested in adding flood endorsement next cycle.", timestamp: "2026-04-19T10:10:00Z" },
    ],
    interactions: [
      { id: "I-1", type: "call", summary: "Renewal walkthrough call (12 min)", timestamp: "2026-05-12T15:22:00Z", actor: "Avery Chen" },
      { id: "I-2", type: "email", summary: "Sent home renewal quote", timestamp: "2026-05-10T09:04:00Z", actor: "Avery Chen" },
      { id: "I-3", type: "system", summary: "Claim CLM-4421 status changed to Under Review", timestamp: "2026-04-25T14:30:00Z", actor: "System" },
      { id: "I-4", type: "meeting", summary: "Annual policy review in-office", timestamp: "2026-03-02T17:00:00Z", actor: "Avery Chen" },
    ],
    insights: [
      { id: "IN-1", severity: "warning", title: "Home renewal in 14 days", detail: "Pending renewal not yet acknowledged. Recommend follow-up call." },
      { id: "IN-2", severity: "opportunity", title: "Flood endorsement missing", detail: "Property is in FEMA Zone X (shaded). Optional flood coverage commonly added." },
      { id: "IN-3", severity: "info", title: "Multi-policy discount applied", detail: "Auto + Home + Umbrella bundle saving 14% annually." },
    ],
  },
  {
    id: "CUS-1078",
    fullName: "Daniel Okafor",
    email: "d.okafor@kintragroup.io",
    phone: "+1 (646) 555-0144",
    address: "1145 W 27th St, Brooklyn, NY 11226",
    assignedAgent: "Marcus Reid",
    status: "needs_attention",
    tags: ["Open claim", "First-year"],
    customerSince: "2025-06-30",
    lifetimeValue: 4120,
    lastInteractionAt: "2026-05-14T11:05:00Z",
    policies: [
      {
        id: "POL-AUT-7785",
        type: "auto",
        provider: "Kintra Auto",
        policyNumber: "KA-7785-DO",
        premium: 1420,
        coverageLimit: 100000,
        renewalDate: "2026-06-30",
        status: "pending_renewal",
        coverageSummary: "Liability + collision, $1000 deductible",
      },
    ],
    claims: [
      { id: "CLM-4502", type: "Collision", status: "pending_documents", amount: 3200, filedAt: "2026-05-02", description: "Side-mirror damage in parking garage." },
      { id: "CLM-4488", type: "Theft", status: "new", amount: 1850, filedAt: "2026-05-12", description: "Reported stolen catalytic converter." },
    ],
    documents: [
      { id: "D-5", name: "Auto_Policy_2025.pdf", category: "policy", sizeKb: 612, uploadedAt: "2025-06-30", status: "indexed" },
      { id: "D-6", name: "Police_Report_CLM4488.pdf", category: "claim", sizeKb: 240, uploadedAt: "2026-05-13", status: "processing" },
    ],
    notes: [
      { id: "N-3", author: "Marcus Reid", message: "Waiting on repair estimate for CLM-4502.", timestamp: "2026-05-08T12:00:00Z" },
    ],
    interactions: [
      { id: "I-5", type: "email", summary: "Requested missing repair invoice", timestamp: "2026-05-14T11:05:00Z", actor: "Marcus Reid" },
      { id: "I-6", type: "call", summary: "Initial claim intake call", timestamp: "2026-05-02T09:15:00Z", actor: "Marcus Reid" },
    ],
    insights: [
      { id: "IN-4", severity: "critical", title: "Multiple active auto claims", detail: "Two claims filed within 10 days. Flag for fraud review per SOP-14." },
      { id: "IN-5", severity: "warning", title: "Renewal at risk", detail: "Open claims may impact renewal premium. Pre-empt with proactive call." },
    ],
  },
  {
    id: "CUS-1091",
    fullName: "Maya Lindqvist",
    email: "maya.l@harboursideco.com",
    phone: "+1 (206) 555-0119",
    address: "3120 Queen Anne Ave N, Seattle, WA 98109",
    assignedAgent: "Priya Shah",
    status: "active",
    tags: ["Family plan"],
    customerSince: "2021-09-04",
    lifetimeValue: 42180,
    lastInteractionAt: "2026-04-30T13:40:00Z",
    policies: [
      { id: "POL-HEA-3301", type: "health", provider: "Harbourside Health", policyNumber: "HH-3301-ML", premium: 5640, coverageLimit: 500000, renewalDate: "2026-12-01", status: "active", coverageSummary: "Family PPO, $2,500 deductible" },
      { id: "POL-AUT-3302", type: "auto", provider: "Northstar Mutual", policyNumber: "NSA-3302-ML", premium: 1180, coverageLimit: 250000, renewalDate: "2026-10-15", status: "active", coverageSummary: "Standard coverage, two vehicles" },
    ],
    claims: [],
    documents: [
      { id: "D-7", name: "Health_Policy_2026.pdf", category: "policy", sizeKb: 1124, uploadedAt: "2025-12-01", status: "indexed" },
    ],
    notes: [
      { id: "N-4", author: "Priya Shah", message: "Customer happy with current plan. No action needed.", timestamp: "2026-04-30T13:40:00Z" },
    ],
    interactions: [
      { id: "I-7", type: "email", summary: "Annual benefits summary sent", timestamp: "2026-04-30T13:40:00Z", actor: "Priya Shah" },
    ],
    insights: [
      { id: "IN-6", severity: "info", title: "Stable account", detail: "No claims in 24 months. Eligible for loyalty discount next cycle." },
    ],
  },
  {
    id: "CUS-1103",
    fullName: "Rafael Moreno",
    email: "rafael@morenoconstruction.co",
    phone: "+1 (305) 555-0166",
    address: "7842 Coral Way, Miami, FL 33155",
    assignedAgent: "Jordan Blake",
    status: "in_review",
    tags: ["Commercial", "Underwriting"],
    customerSince: "2023-01-22",
    lifetimeValue: 96400,
    lastInteractionAt: "2026-05-09T16:00:00Z",
    policies: [
      { id: "POL-COM-5510", type: "commercial", provider: "Atlas Commercial", policyNumber: "AC-5510-RM", premium: 14820, coverageLimit: 5000000, renewalDate: "2026-07-22", status: "pending_renewal", coverageSummary: "General liability + commercial auto fleet (8 vehicles)" },
    ],
    claims: [
      { id: "CLM-4380", type: "Liability", status: "closed", amount: 22400, filedAt: "2025-08-19", description: "Worksite slip-and-fall, settled out of court." },
    ],
    documents: [
      { id: "D-8", name: "Commercial_Master_Policy.pdf", category: "policy", sizeKb: 2880, uploadedAt: "2025-07-22", status: "indexed" },
      { id: "D-9", name: "Fleet_VIN_List.xlsx", category: "other", sizeKb: 84, uploadedAt: "2026-03-01", status: "indexed" },
    ],
    notes: [
      { id: "N-5", author: "Jordan Blake", message: "Underwriting requested updated fleet list for renewal.", timestamp: "2026-05-09T16:00:00Z", pinned: true },
    ],
    interactions: [
      { id: "I-8", type: "meeting", summary: "Renewal underwriting review", timestamp: "2026-05-09T16:00:00Z", actor: "Jordan Blake" },
      { id: "I-9", type: "email", summary: "Fleet VIN list received", timestamp: "2026-03-01T09:20:00Z", actor: "Rafael Moreno" },
    ],
    insights: [
      { id: "IN-7", severity: "warning", title: "Fleet size increased 33%", detail: "Vehicle count grew from 6 to 8 since last renewal. Re-rate required." },
      { id: "IN-8", severity: "opportunity", title: "Workers' comp cross-sell", detail: "Construction class code without WC policy on file." },
    ],
  },
  {
    id: "CUS-1129",
    fullName: "Hannah Park",
    email: "hannah.park@meridianlaw.com",
    phone: "+1 (312) 555-0107",
    address: "640 N State St, Chicago, IL 60654",
    assignedAgent: "Sofia Martinez",
    status: "active",
    tags: ["Life", "Beneficiary updated"],
    customerSince: "2019-11-18",
    lifetimeValue: 28940,
    lastInteractionAt: "2026-03-22T10:15:00Z",
    policies: [
      { id: "POL-LIF-6620", type: "life", provider: "Meridian Life", policyNumber: "ML-6620-HP", premium: 1240, coverageLimit: 750000, renewalDate: "2027-01-10", status: "active", coverageSummary: "20-year term life, beneficiary: spouse" },
    ],
    claims: [],
    documents: [
      { id: "D-10", name: "Life_Policy_Term.pdf", category: "policy", sizeKb: 540, uploadedAt: "2024-01-10", status: "indexed" },
      { id: "D-11", name: "Beneficiary_Update_2026.pdf", category: "endorsement", sizeKb: 96, uploadedAt: "2026-03-22", status: "indexed" },
    ],
    notes: [],
    interactions: [
      { id: "I-10", type: "email", summary: "Beneficiary form processed", timestamp: "2026-03-22T10:15:00Z", actor: "Sofia Martinez" },
    ],
    insights: [
      { id: "IN-9", severity: "info", title: "Coverage gap analysis", detail: "Term coverage matches income for 8 years; recommended is 10x annual income." },
    ],
  },
  {
    id: "CUS-1145",
    fullName: "Tomás Ribeiro",
    email: "tomas.r@gmail.com",
    phone: "+1 (713) 555-0193",
    address: "915 Heights Blvd, Houston, TX 77008",
    assignedAgent: "Avery Chen",
    status: "needs_attention",
    tags: ["Lapsed payment"],
    customerSince: "2022-04-10",
    lifetimeValue: 9820,
    lastInteractionAt: "2026-05-01T08:30:00Z",
    policies: [
      { id: "POL-AUT-8810", type: "auto", provider: "Northstar Mutual", policyNumber: "NSA-8810-TR", premium: 1620, coverageLimit: 200000, renewalDate: "2026-06-10", status: "lapsed", coverageSummary: "Standard coverage, lapsed 2026-05-01" },
    ],
    claims: [],
    documents: [
      { id: "D-12", name: "Auto_Policy_Lapse_Notice.pdf", category: "policy", sizeKb: 142, uploadedAt: "2026-05-01", status: "indexed" },
    ],
    notes: [
      { id: "N-6", author: "Avery Chen", message: "Payment failed twice. Left voicemail.", timestamp: "2026-05-01T08:30:00Z" },
    ],
    interactions: [
      { id: "I-11", type: "sms", summary: "Reinstatement reminder sent", timestamp: "2026-05-05T14:00:00Z", actor: "System" },
      { id: "I-12", type: "call", summary: "Voicemail re: lapsed policy", timestamp: "2026-05-01T08:30:00Z", actor: "Avery Chen" },
    ],
    insights: [
      { id: "IN-10", severity: "critical", title: "Policy lapsed", detail: "Auto policy lapsed 12 days ago. Coverage gap exposure." },
    ],
  },
];
