import type { Claim, ClaimComment, TimelineEvent } from "./types";

const AGENTS = [
  "Sarah Chen",
  "Marcus Johnson",
  "Priya Patel",
  "David Kim",
  "Elena Rodriguez",
  "James O'Brien",
];

export const MOCK_AGENTS = AGENTS;

export const MOCK_CLAIMS: Claim[] = [
  {
    id: "CLM-10248",
    customerName: "Olivia Bennett",
    customerEmail: "olivia.bennett@example.com",
    policyNumber: "POL-AUTO-44829",
    policyType: "auto",
    claimType: "collision",
    status: "under_review",
    priority: "high",
    assignedAgent: "Sarah Chen",
    amount: 12450,
    description:
      "Rear-end collision at intersection of 5th and Main. Vehicle bumper and tail-light damage.",
    incidentDate: "2026-05-08",
    createdAt: "2026-05-09T14:22:00Z",
    updatedAt: "2026-05-14T09:11:00Z",
    attachments: [
      { id: "att-1", name: "police-report.pdf", sizeKb: 482 },
      { id: "att-2", name: "vehicle-photos.zip", sizeKb: 8120 },
    ],
  },
  {
    id: "CLM-10247",
    customerName: "Daniel Foster",
    customerEmail: "d.foster@example.com",
    policyNumber: "POL-HOME-22011",
    policyType: "home",
    claimType: "natural_disaster",
    status: "pending_documents",
    priority: "urgent",
    assignedAgent: "Marcus Johnson",
    amount: 48200,
    description: "Storm damage to roof and second-floor windows during May 6 windstorm.",
    incidentDate: "2026-05-06",
    createdAt: "2026-05-07T08:01:00Z",
    updatedAt: "2026-05-13T17:42:00Z",
    attachments: [{ id: "att-3", name: "damage-estimate.pdf", sizeKb: 1240 }],
  },
  {
    id: "CLM-10246",
    customerName: "Aisha Khan",
    customerEmail: "aisha.k@example.com",
    policyNumber: "POL-HEALTH-90183",
    policyType: "health",
    claimType: "medical",
    status: "approved",
    priority: "medium",
    assignedAgent: "Priya Patel",
    amount: 3820,
    description: "Outpatient procedure reimbursement, in-network provider.",
    incidentDate: "2026-04-28",
    createdAt: "2026-05-01T10:15:00Z",
    updatedAt: "2026-05-12T11:30:00Z",
    attachments: [],
  },
  {
    id: "CLM-10245",
    customerName: "Henry Walsh",
    customerEmail: "henry.walsh@example.com",
    policyNumber: "POL-AUTO-31290",
    policyType: "auto",
    claimType: "theft",
    status: "new",
    priority: "high",
    assignedAgent: "David Kim",
    amount: 22000,
    description: "Vehicle stolen from residential driveway overnight.",
    incidentDate: "2026-05-13",
    createdAt: "2026-05-14T07:42:00Z",
    updatedAt: "2026-05-14T07:42:00Z",
    attachments: [{ id: "att-4", name: "police-incident.pdf", sizeKb: 312 }],
  },
  {
    id: "CLM-10244",
    customerName: "Sophia Müller",
    customerEmail: "sophia.m@example.com",
    policyNumber: "POL-COMM-77821",
    policyType: "commercial",
    claimType: "liability",
    status: "under_review",
    priority: "medium",
    assignedAgent: "Elena Rodriguez",
    amount: 18500,
    description: "Slip and fall incident at retail location, third-party liability claim.",
    incidentDate: "2026-04-22",
    createdAt: "2026-04-25T13:00:00Z",
    updatedAt: "2026-05-11T15:20:00Z",
    attachments: [],
  },
  {
    id: "CLM-10243",
    customerName: "Marcus Lee",
    customerEmail: "m.lee@example.com",
    policyNumber: "POL-HOME-55510",
    policyType: "home",
    claimType: "property_damage",
    status: "rejected",
    priority: "low",
    assignedAgent: "James O'Brien",
    amount: 1250,
    description: "Minor water damage from appliance leak. Coverage exclusion applies.",
    incidentDate: "2026-04-10",
    createdAt: "2026-04-12T09:30:00Z",
    updatedAt: "2026-05-02T14:00:00Z",
    attachments: [],
  },
  {
    id: "CLM-10242",
    customerName: "Yuki Tanaka",
    customerEmail: "y.tanaka@example.com",
    policyNumber: "POL-LIFE-19283",
    policyType: "life",
    claimType: "medical",
    status: "closed",
    priority: "medium",
    assignedAgent: "Sarah Chen",
    amount: 75000,
    description: "Beneficiary claim — processed and disbursed.",
    incidentDate: "2026-03-18",
    createdAt: "2026-03-22T11:00:00Z",
    updatedAt: "2026-04-30T10:00:00Z",
    attachments: [],
  },
  {
    id: "CLM-10241",
    customerName: "Rachel Adebayo",
    customerEmail: "rachel.a@example.com",
    policyNumber: "POL-AUTO-66432",
    policyType: "auto",
    claimType: "collision",
    status: "pending_documents",
    priority: "low",
    assignedAgent: "Marcus Johnson",
    amount: 4200,
    description: "Parking lot fender-bender. Awaiting other party's insurance information.",
    incidentDate: "2026-05-04",
    createdAt: "2026-05-05T16:18:00Z",
    updatedAt: "2026-05-10T12:00:00Z",
    attachments: [],
  },
];

export const MOCK_COMMENTS: ClaimComment[] = [
  {
    id: "c-1",
    claimId: "CLM-10248",
    user: "Sarah Chen",
    message:
      "Reviewed police report. Estimate seems within range. Requesting body shop quotes before approval.",
    timestamp: "2026-05-13T15:24:00Z",
    internal: true,
  },
  {
    id: "c-2",
    claimId: "CLM-10248",
    user: "David Kim",
    message: "Customer called to follow up — provided ETA of 5 business days.",
    timestamp: "2026-05-14T09:10:00Z",
    internal: false,
  },
  {
    id: "c-3",
    claimId: "CLM-10247",
    user: "Marcus Johnson",
    message: "Need updated contractor estimate and proof of pre-loss condition.",
    timestamp: "2026-05-13T17:42:00Z",
    internal: true,
  },
];

export const MOCK_TIMELINE: TimelineEvent[] = [
  {
    id: "t-1",
    claimId: "CLM-10248",
    type: "created",
    description: "Claim filed by customer via web portal",
    actor: "Olivia Bennett",
    timestamp: "2026-05-09T14:22:00Z",
  },
  {
    id: "t-2",
    claimId: "CLM-10248",
    type: "agent_assigned",
    description: "Assigned to Sarah Chen",
    actor: "System",
    timestamp: "2026-05-09T14:25:00Z",
  },
  {
    id: "t-3",
    claimId: "CLM-10248",
    type: "document_uploaded",
    description: "police-report.pdf uploaded",
    actor: "Olivia Bennett",
    timestamp: "2026-05-10T11:02:00Z",
  },
  {
    id: "t-4",
    claimId: "CLM-10248",
    type: "status_changed",
    description: "Status changed from New to Under Review",
    actor: "Sarah Chen",
    timestamp: "2026-05-11T09:18:00Z",
  },
  {
    id: "t-5",
    claimId: "CLM-10248",
    type: "note_added",
    description: "Internal note added by Sarah Chen",
    actor: "Sarah Chen",
    timestamp: "2026-05-13T15:24:00Z",
  },
  {
    id: "t-6",
    claimId: "CLM-10247",
    type: "created",
    description: "Claim filed by adjuster on behalf of customer",
    actor: "Marcus Johnson",
    timestamp: "2026-05-07T08:01:00Z",
  },
  {
    id: "t-7",
    claimId: "CLM-10247",
    type: "status_changed",
    description: "Status changed to Pending Documents",
    actor: "Marcus Johnson",
    timestamp: "2026-05-08T10:00:00Z",
  },
];
